### PR TITLE
Java compatability

### PR DESCRIPTION
**Pull request by maciej-zygmunt**
Small changes to compile with ant.

### CODE REVIEW

**Comment by tomas-muller** [comment]
Next time, please use more informative commit messages. The message should contain the name of the component and a short description in the title (first line). Something like:

AGH Course Details Provider: Java compatibility fix

**Comment by tomas-muller** [comment]
I have pushed back all your changes. Please send me a new pull request that contains only one commit with the file and a meaningful commit message.

Thanks,
Tomas

**Comment by maciej-zygmunt** [comment]
Thanks, I am learning Git and open source culture. I will create next 
pull request as suggested in the next email.


W dniu 02.01.2017 o 23:50, Tomáš Müller pisze:

**Comment by tomas-muller** [comment]
I have rebased all your changes into one commit 53cbdd that is now both in UniTime 4.1 (master branch) and UniTime 4.2 (dev_UniTime42 branch).

**Comment by maciej-zygmunt** [comment]
Thanks, I will learn how to use Git on next commits.


Cheers,

Maciej


W dniu 09.01.2017 o 09:36, Tomáš Müller pisze:

**Pull request merged**
